version: '3'

services:

  # The Git hook installer service makes sure to install the pre-commit hook for checking code standards
  githook-installer:
    build:
      context: .
      dockerfile: Dockerfile.githooks
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks

  # The base image on which all other images are based
  base:
    image: entity-salience-base
    build:
      context: .
      dockerfile: Dockerfile.base

  # The lab image extends the base images with Jupyter lab
  lab:
    build:
      context: .
      dockerfile: Dockerfile.lab
    depends_on:
      - base
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    command: sh -c "jupyter lab --no-browser --ip '*' --NotebookApp.token='' --allow-root --notebook-dir='/code/notebooks/'"
    volumes:
      - .:/code

  # The run-checks image extends the base image with code standard checks and testing tools
  run-checks:
    build:
      context: .
      dockerfile: Dockerfile.checks
    depends_on:
      - base
    command: sh -c "make checks"
    volumes:
      - .:/code

  # The entity-salience image is the base image including the source code
  entity-salience:
    image: kevin91nl/entity-salience
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - base
    command: sh -c "python"
    volumes:
      - .:/code
